In [115]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn import preprocessing

In [116]:
raw_data = pd.read_csv('D:\\Data Science\\Datasets\\Datasets\\Audiobooks_data.csv', header=None)
raw_data.head()

0       1     2      3      4   5     6    7    8   9    10  11
0  873  2160.0  2160  10.13  10.13   0  8.91  0.0  0.0   0    0   1
1  611  1404.0  2808   6.66  13.33   1  6.50  0.0  0.0   0  182   1
2  705   324.0   324  10.13  10.13   1  9.00  0.0  0.0   1  334   1
3  391  1620.0  1620  15.31  15.31   0  9.00  0.0  0.0   0  183   1
4  819   432.0  1296   7.11  21.33   1  9.00  0.0  0.0   0    0   1

In [117]:
raw_data.isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
dtype: int64

In [118]:
data1 = pd.DataFrame()
count = 0
data1 = raw_data[raw_data[11]==1]

In [119]:
data0 = pd.DataFrame()
for i in range(11000):
    if data[data[11]==1].shape[0] == count:
        break
    else:
        if raw_data.iloc[i][11] == 0:
            toappend = raw_data.iloc[i].to_dict()
            data0 = data0.append(toappend, ignore_index=True)
            #print (toappend)
            count = count+1

In [125]:
data0.shape

(2237, 12)

In [126]:
data1.shape

(2237, 12)

In [130]:
data = pd.concat([data0, data1])

In [131]:
data.reset_index(drop=True, inplace=True)

In [133]:
data.drop([0], inplace=True, axis=1)

In [134]:
data

1       2      3      4    5      6     7    8    9      10   11
0     1080.0  1080.0  10.13  10.13  1.0   9.00  0.85  0.0  1.0   81.0  0.0
1     2160.0  2160.0   5.33   5.33  0.0   8.91  0.00  0.0  0.0   37.0  0.0
2      648.0   648.0  10.13  10.13  1.0   8.00  0.65  0.0  0.0  134.0  0.0
3     2160.0  2160.0   8.00   8.00  0.0   8.91  0.58  0.0  0.0  138.0  0.0
4     1620.0  1620.0   8.96   8.96  0.0   8.91  0.09  0.0  0.0    0.0  0.0
...      ...     ...    ...    ...  ...    ...   ...  ...  ...    ...  ...
4469  1620.0  1620.0   5.33   5.33  0.0   8.91  0.00  0.0  0.0    0.0  1.0
4470  1476.0  4428.0   5.33  16.00  0.0   8.91  0.00  0.0  0.0    0.0  1.0
4471  2160.0  2160.0   5.33   5.33  0.0   8.91  0.00  0.0  0.0   12.0  1.0
4472  2160.0  2160.0   5.33   5.33  1.0  10.00  0.00  0.0  0.0    6.0  1.0
4473  1674.0  3348.0   7.99  15.99  0.0   8.91  0.00  0.0  0.0    0.0  1.0

[4474 rows x 11 columns]

In [135]:
inputs = data.drop([11], axis=1)
output = data[11]

In [136]:
scaler = preprocessing.StandardScaler()

In [137]:
scaled_inputs = scaler.fit_transform(inputs)

In [138]:
scaled_inputs

array([[-0.98156725, -0.87676153,  0.67728889, ..., -0.8635056 ,
         2.23179102,  0.08984327],
       [ 1.18956512,  0.36398846, -0.38189654, ..., -0.8635056 ,
        -0.20536617, -0.37854093],
       [-1.8500202 , -1.37306153,  0.67728889, ..., -0.8635056 ,
        -0.20536617,  0.65403333],
       ...,
       [ 1.18956512,  0.36398846, -0.38189654, ..., -0.8635056 ,
        -0.20536617, -0.64466831],
       [ 1.18956512,  0.36398846, -0.38189654, ..., -0.8635056 ,
        -0.20536617, -0.70853889],
       [ 0.21255556,  1.72881345,  0.20506872, ..., -0.8635056 ,
        -0.20536617, -0.77240946]])

In [139]:
shuffled_indices = np.arange(inputs.shape[0])
np.random.shuffle(shuffled_indices)
shuffled_inputs = scaled_inputs[shuffled_indices]
shuffled_outputs = output[shuffled_indices]

In [140]:
shuffled_outputs

3376    1.0
444     0.0
2253    1.0
2118    0.0
4344    1.0
       ... 
332     0.0
397     0.0
4100    1.0
1284    0.0
1486    0.0
Name: 11, Length: 4474, dtype: float64

In [154]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(shuffled_inputs, shuffled_outputs, test_size=0.1, random_state=365)

In [155]:
validation_size = int(x_train.shape[0]/10)
x_validation = x_train[:validation_size]
x_train = x_train[validation_size:x_train.shape[0]]

y_validation = y_train[:validation_size]
y_train = y_train[validation_size:y_train.shape[0]]

In [156]:
print (x_train.shape, y_train.shape)
print (x_test.shape, y_test.shape)
print (x_validation.shape, y_validation.shape)

(3624, 10) (3624,)
(448, 10) (448,)
(402, 10) (402,)


In [159]:
np.savez('D:\\Data Science\\Datasets\\Datasets\\npz_files\\ATrain.npz', inputs=x_train, targets=y_train)
np.savez('D:\\Data Science\\Datasets\\Datasets\\npz_files\\ATest.npz', inputs=x_test, targets=y_test)
np.savez('D:\\Data Science\\Datasets\\Datasets\\npz_files\\AValidation.npz', inputs=x_validation, targets=y_validation)

In [173]:
input_size = 10
depth = 50
output_size = 2
batch_size = 100
max_epochs = 100
early_stopping = tf.keras.callbacks.EarlyStopping(patience=2)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(depth, activation='relu'),
    tf.keras.layers.Dense(depth, activation='relu'),
    tf.keras.layers.Dense(output_size, activation='softmax')
])
model.compile(optimizer='Adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train,
            y_train,
            epochs=max_epochs,
            batch_size=batch_size,
            validation_data=(x_validation, y_validation),
            verbose=2,
             callbacks = [early_stopping])

Epoch 1/100
37/37 - 0s - loss: 0.6321 - accuracy: 0.6719 - val_loss: 0.5147 - val_accuracy: 0.7960
Epoch 2/100
37/37 - 0s - loss: 0.4217 - accuracy: 0.8620 - val_loss: 0.4098 - val_accuracy: 0.8582
Epoch 3/100
37/37 - 0s - loss: 0.3360 - accuracy: 0.8753 - val_loss: 0.3721 - val_accuracy: 0.8682
Epoch 4/100
37/37 - 0s - loss: 0.3052 - accuracy: 0.8852 - val_loss: 0.3433 - val_accuracy: 0.8731
Epoch 5/100
37/37 - 0s - loss: 0.2898 - accuracy: 0.8902 - val_loss: 0.3225 - val_accuracy: 0.8781
Epoch 6/100
37/37 - 0s - loss: 0.2775 - accuracy: 0.8957 - val_loss: 0.3079 - val_accuracy: 0.8806
Epoch 7/100
37/37 - 0s - loss: 0.2684 - accuracy: 0.8987 - val_loss: 0.2986 - val_accuracy: 0.8831
Epoch 8/100
37/37 - 0s - loss: 0.2622 - accuracy: 0.8993 - val_loss: 0.2907 - val_accuracy: 0.8831
Epoch 9/100
37/37 - 0s - loss: 0.2574 - accuracy: 0.9009 - val_loss: 0.2877 - val_accuracy: 0.8856
Epoch 10/100
37/37 - 0s - loss: 0.2544 - accuracy: 0.9031 - val_loss: 0.2861 - val_accuracy: 0.8856
Epoch 11/

In [165]:
x_validation.shape

(402, 10)

In [177]:
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(test_loss, test_accuracy)

14/14 [==============================] - 0s 715us/step - loss: 0.2333 - accuracy: 0.9196
0.23327016830444336 0.9196428656578064


In [184]:
predictions = model.predict(x_test)

In [194]:
np.asarray(predictions)

array([[8.44631672e-01, 1.55368283e-01],
       [1.62850082e-01, 8.37149918e-01],
       [1.00000000e+00, 4.34990284e-08],
       [9.99992847e-01, 7.20322350e-06],
       [9.91468191e-01, 8.53184983e-03],
       [2.69084513e-01, 7.30915546e-01],
       [5.80593696e-05, 9.99941945e-01],
       [9.98980582e-01, 1.01935270e-03],
       [2.00858384e-01, 7.99141645e-01],
       [9.99991775e-01, 8.23066239e-06],
       [6.14954931e-09, 1.00000000e+00],
       [9.64211583e-01, 3.57883573e-02],
       [7.68488705e-01, 2.31511354e-01],
       [2.69084513e-01, 7.30915546e-01],
       [1.57407954e-01, 8.42592061e-01],
       [9.18957829e-01, 8.10421929e-02],
       [2.55228490e-01, 7.44771481e-01],
       [6.47211909e-01, 3.52788121e-01],
       [8.28212619e-01, 1.71787322e-01],
       [9.99805748e-01, 1.94272056e-04],
       [1.44057572e-01, 8.55942428e-01],
       [1.29728243e-01, 8.70271802e-01],
       [1.64823383e-01, 8.35176587e-01],
       [8.37193608e-01, 1.62806436e-01],
       [1.871384

In [195]:
np.set_printoptions(suppress=True)
predictions

array([[0.8446317 , 0.15536828],
       [0.16285008, 0.8371499 ],
       [1.        , 0.00000004],
       [0.99999285, 0.0000072 ],
       [0.9914682 , 0.00853185],
       [0.2690845 , 0.73091555],
       [0.00005806, 0.99994195],
       [0.9989806 , 0.00101935],
       [0.20085838, 0.79914165],
       [0.9999918 , 0.00000823],
       [0.00000001, 1.        ],
       [0.9642116 , 0.03578836],
       [0.7684887 , 0.23151135],
       [0.2690845 , 0.73091555],
       [0.15740795, 0.84259206],
       [0.9189578 , 0.08104219],
       [0.2552285 , 0.7447715 ],
       [0.6472119 , 0.35278812],
       [0.8282126 , 0.17178732],
       [0.99980575, 0.00019427],
       [0.14405757, 0.8559424 ],
       [0.12972824, 0.8702718 ],
       [0.16482338, 0.8351766 ],
       [0.8371936 , 0.16280644],
       [0.18713845, 0.81286156],
       [1.        , 0.        ],
       [0.04132427, 0.9586757 ],
       [0.87229437, 0.12770563],
       [0.69921   , 0.30079   ],
       [0.9999894 , 0.00001057],
       [0.

In [196]:
from sklearn.ensemble import RandomForestClassifier

In [207]:
model = RandomForestClassifier(n_estimators=37)

In [208]:
model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=37)

In [209]:
model.score(x_test, y_test)

0.8995535714285714